# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9584a9fbfe228f470a8b53d30e74b13cba22150abe1daea8b77e52d5347b5d5ce4da31417ed6db97200c064e22a7ac8bb7993de4280f73e42bf0eb47fd8e9a2b

test:
  secret_key_base: e1b5025d4266250acc54c8bb05ffd269de287e0d5cfd72c7fd0684fd6e3ec1527a3d1ca412881f5c1a215896d3346e1cfcfa052ec1cf97901909ac726264697f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
